favicon: /favicon.ico
banner: /images/webstack_banner_cn.png

logo:
  expanded: /images/logo@2x.png
  collapsed: /images/logo-collapsed@2x.png
  dark: /images/logo_dark@2x.png

flag:
  icon: flag-cn
  name: Chinese



menu:
  - name: 我的网站
    icon: far fa-star
    config: hotTools
  - name: 资讯网站
    icon: fas fa-blog
    config: news
  - name: 通讯工具
    icon: fas fa-paper-plane
    config: imTools
  - name: 网站工具
    icon: fas fa-tools
    config: devTools
      

devTools:
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 代码仓库
  - name: cron
    url: https://cron.qqe2.com/
    img: /images/logos/github.png
    description: cron在线表达式
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 代码仓库
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 代码仓库
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 代码仓库
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 代码仓库
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 代码仓库
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 代码仓库
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 代码仓库
  
hotTools:
  - name: ChatGPT
    url: https://chat.yohaoyun.com/
    img: /images/logos/blog-logo.png
    description: 欢迎访问
  - name: 当前时间戳
    url: https://www.xb02.com/tool/time/
    img: /images/logos/github.png
    description: 当前时间戳生成工具
  - name: 时间戳转换
    url: https://tool.lu/timestamp/
    img: /images/logos/github.png
    description: 时间戳转换
  - name: 在线URL转换
    url: http://www.jsons.cn/urlencode
    img: /images/logos/github.png
    description: 在线URL转换
  - name: 网络空间测绘
    url: https://fofa.info/
    img: /images/logos/github.png
    description: 网络空间测绘
  - name: 机场推荐
    url: https://github.com/hwanz/SSR-V2ray-Trojan-vpn
    img: /images/logos/github.png
    description: 机场推荐
  - name: FNF
    url: https://fnff.one/auth/login
    img: /images/logos/github.png
    description: 便宜的机场
  - name: V2ray一键搭建脚本
    url: https://github.com/233boy/v2ray/tree/master
    img: /images/logos/github.png
    description: 一键搭建脚本的官网
   
news:
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 代码仓库
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 代码仓库
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 代码仓库
  
about:
  url: /about/
  icon: far fa-heart
  name: 关于本站

aboutPage:
  website:
    head: 欢迎回家！
    html: '<blockquote><p>这是一个WebStack网址导航网站，源于ViggoZ的开源项目，开源地址<a href="https://github.com/WebStackPage/WebStackPage.github.io" target="_blank" rel="noopener">WebStackPage</a>。</p>
 本导航站基于hexo博客程序、<a href="https://github.com/HCLonely/hexo-theme-webstack" target="_blank" rel="noopener">hexo-theme-webstack</a>主题模板、github、vercel 搭建而成。</p></blockquote>'
  webmaster:
    head: 关于主站
    name: 个人记录导航站
    url: https://nav.yohaoyun.com
    img: /images/logos/blog-logo.png
    description: 世上无难事，只要肯登攀。
    html: '<br /><blockquote><p>功夫不负有心人！</p></blockquote>'

since: 2020

busuanzi:
  enable: true
  position: sidebar # 'footer','sidebar'
  pv: 本站总访问量$pv
  uv: 本站总访客数$uv

custom:
  head: |- # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->
  body: |- # 以下内容插入到</body>标签之前，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->

js:
  header: /js/header.js
  footer: /js/footer.js
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /js/bootstrap.min.js
  TweenMax: /js/TweenMax.min.js
  resizeable: /js/resizeable.min.js
  joinable: /js/joinable.js
  xenonApi: /js/xenon-api.min.js
  xenonToggles: /js/xenon-toggles.min.js
  xenonCustom: /js/xenon-custom.min.js
  lozad: /js/lozad.min.js
  html5shiv: /js/html5shiv.min.js
  respond: /js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: /css/hclonely.css
  fonts: //fonts.loli.net/css?family=Arimo:400,700,400italic
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css
